package sistemademarcado;

import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 * @author John Granados
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        nombre_lbl = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        apellido_lbl = new javax.swing.JLabel();
        apellido_txt = new javax.swing.JTextField();
        dir_lbl = new javax.swing.JLabel();
        dir_txt = new javax.swing.JTextField();
        ced_lbl = new javax.swing.JLabel();
        ced_txt = new javax.swing.JTextField();
        pass_lbl = new javax.swing.JLabel();
        pass_txt = new javax.swing.JPasswordField();
        fechnac_lbl = new javax.swing.JLabel();
        fechnac_txt = new javax.swing.JFormattedTextField();
        area_lbl = new javax.swing.JLabel();
        cargo_lbl = new javax.swing.JLabel();
        cargo_txt = new javax.swing.JTextField();
        nac_lbl = new javax.swing.JLabel();
        nac_txt = new javax.swing.JTextField();
        tel_lbl = new javax.swing.JLabel();
        tel_txt = new javax.swing.JTextField();
        cel_lbl = new javax.swing.JLabel();
        cel_txt = new javax.swing.JTextField();
        email_lbl = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        genero_lbl = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        guardar_btn = new javax.swing.JButton();
        modificar_btn = new javax.swing.JButton();
        eliminar_btn = new javax.swing.JButton();
        cancelar_btn = new javax.swing.JButton();
        idpersonal_lbl = new javax.swing.JLabel();
        idpersonal_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        area_cbx = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Usuarios");
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(0, 156, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        nombre_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nombre_lbl.setText("Nombre");

        apellido_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apellido_lbl.setForeground(new java.awt.Color(255, 255, 255));
        apellido_lbl.setText("Apellido");

        dir_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dir_lbl.setForeground(new java.awt.Color(255, 255, 255));
        dir_lbl.setText("Dirección");

        ced_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ced_lbl.setForeground(new java.awt.Color(255, 255, 255));
        ced_lbl.setText("Cédula");

        pass_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pass_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pass_lbl.setText("Contraseña");

        fechnac_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechnac_lbl.setForeground(new java.awt.Color(255, 255, 255));
        fechnac_lbl.setText("Fecha de Nacimiento");

        fechnac_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        area_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        area_lbl.setForeground(new java.awt.Color(255, 255, 255));
        area_lbl.setText("Área");

        cargo_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cargo_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cargo_lbl.setText("Cargo");

        nac_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nac_lbl.setForeground(new java.awt.Color(255, 255, 255));
        nac_lbl.setText("Nacionalidad");

        tel_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tel_lbl.setForeground(new java.awt.Color(255, 255, 255));
        tel_lbl.setText("Teléfono");

        cel_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cel_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cel_lbl.setText("Celular");

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email_lbl.setForeground(new java.awt.Color(255, 255, 255));
        email_lbl.setText("E-Mail");

        genero_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genero_lbl.setForeground(new java.awt.Color(255, 255, 255));
        genero_lbl.setText("Género");

        jRadioButton1.setBackground(new java.awt.Color(0, 156, 180));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Masculino");

        jRadioButton2.setBackground(new java.awt.Color(0, 156, 180));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Femenino");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Dirección", "Cédula", "Contraseña", "Fecha de Nacimiento", "Área", "Cargo", "Nacionalidad", "Teléfono", "Celular", "Emaill", "Género"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(11).setResizable(false);
        }

        guardar_btn.setText("Guardar");
        guardar_btn.setToolTipText("");
        guardar_btn.setPreferredSize(new java.awt.Dimension(171, 105));
        guardar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_btnActionPerformed(evt);
            }
        });

        modificar_btn.setText("Modificar");
        modificar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_btnActionPerformed(evt);
            }
        });

        eliminar_btn.setText("Eliminar");
        eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btnActionPerformed(evt);
            }
        });

        cancelar_btn.setText("Cancelar");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        idpersonal_lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idpersonal_lbl.setForeground(new java.awt.Color(255, 255, 255));
        idpersonal_lbl.setText("ID");

        idpersonal_txt.setEditable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemademarcado/uamlogo.png"))); // NOI18N

        area_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Académico", "Administración", "Contabilidad", "Informática", "Seguridad", "Limpieza", "Audiovisual", "Legal" }));
        area_cbx.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(apellido_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellido_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dir_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dir_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ced_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ced_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pass_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fechnac_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechnac_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(area_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(area_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(idpersonal_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpersonal_txt)
                            .addComponent(nombre_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cargo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addComponent(nac_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tel_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cel_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genero_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addComponent(cargo_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nac_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tel_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cel_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email_txt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(307, 307, 307))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelar_btn, eliminar_btn, guardar_btn, modificar_btn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargo_lbl)
                    .addComponent(cargo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpersonal_lbl)
                    .addComponent(idpersonal_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nac_lbl)
                            .addComponent(nac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel_lbl)
                            .addComponent(tel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cel_lbl)
                            .addComponent(cel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_lbl)
                            .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genero_lbl)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificar_btn)
                            .addComponent(eliminar_btn)
                            .addComponent(cancelar_btn)
                            .addComponent(guardar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_lbl)
                            .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido_lbl)
                            .addComponent(apellido_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dir_lbl)
                            .addComponent(dir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ced_lbl)
                            .addComponent(ced_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass_lbl)
                            .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechnac_lbl)
                            .addComponent(fechnac_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(area_lbl)
                            .addComponent(area_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {apellido_txt, cargo_txt, ced_txt, cel_txt, dir_txt, email_txt, fechnac_txt, nac_txt, nombre_txt, pass_txt, tel_txt});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelar_btn, eliminar_btn, guardar_btn, modificar_btn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelar_btnActionPerformed

    private void guardar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_btnActionPerformed

        try {

            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost/sistema_marcado";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "123");

            String nombre = nombre_txt.getText();
            String apellido = apellido_txt.getText();
            String direccion = dir_txt.getText();
            String cedula = ced_txt.getText();
            char[] pass = pass_txt.getPassword();
            String passString = new String(pass);
            String fechnac = fechnac_txt.getText();
            String area = (String) area_cbx.getSelectedItem();
            String cargo = cargo_txt.getText();
            String nacionalidad = nac_txt.getText();
            String telefono = tel_txt.getText();
            String celular = cel_txt.getText();
            String email = email_txt.getText();
            String genero = "";
            if (jRadioButton1.isSelected()) {
                genero = jRadioButton1.getText();
            } else {
                genero = jRadioButton2.getText();
            }
            String query = " insert into personal (id_personal,nombre_personal, apellido_personal, direccion_personal, cedula_personal, pass_personal,fechnac_personal,area_personal,cargo_personal,nacionalidad_personal,telefono_personal,celular_personal,email_personal,genero_personal)"
                    + "values (NULL,'" + nombre + "', '" + apellido + "','" + direccion + "','" + cedula + "','" + passString + "','" + fechnac + "','" + area + "','" + cargo + "','" + nacionalidad + "','" + telefono + "',"
                    + "'" + celular + "','" + email + "','" + genero + "');";

            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.execute();
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }

        actualizar();
    }//GEN-LAST:event_guardar_btnActionPerformed

    private void eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btnActionPerformed

        Conexion CONN = new Conexion();
        String idpersonal = idpersonal_txt.getText();
        CONN.CONECTAR();
        CONN.EJECUTAR("DELETE FROM personal WHERE id_personal = " + idpersonal + "");
        CONN.CERRAR();
        JOptionPane.showMessageDialog(null, "¡Registro borrado exitosamente!");
        limpiar();
        actualizar();
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_btnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {

            int row = jTable1.getSelectedRow();
            String Table_click = (jTable1.getModel().getValueAt(row, 0).toString());

            Conexion CONN = new Conexion();
            CONN.CONECTAR();
            ResultSet rs = CONN.CONSULTAR("SELECT * FROM personal WHERE id_personal='" + Table_click + "'");

            if (rs.next()) {

                String id = rs.getString("id_personal");
                idpersonal_txt.setText(id);
                String nombre = rs.getString("nombre_personal");
                nombre_txt.setText(nombre);
                String apellido = rs.getString("apellido_personal");
                apellido_txt.setText(apellido);
                String direccion = rs.getString("direccion_personal");
                dir_txt.setText(direccion);
                String cedula = rs.getString("cedula_personal");
                ced_txt.setText(cedula);
                String pass = rs.getString("pass_personal");
                pass_txt.setText(pass);
                String fechnac = rs.getString("fechnac_personal");
                fechnac_txt.setText(fechnac);
                String area = rs.getString("area_personal");
                area_cbx.setSelectedItem(area);
                String cargo = rs.getString("cargo_personal");
                cargo_txt.setText(cargo);
                String nacionalidad = rs.getString("nacionalidad_personal");
                nac_txt.setText(nacionalidad);
                String telefono = rs.getString("telefono_personal");
                tel_txt.setText(telefono);
                String celular = rs.getString("celular_personal");
                cel_txt.setText(celular);
                String email = rs.getString("email_personal");
                email_txt.setText(apellido);
                String genero = rs.getString("genero_personal");
                if (genero.equals("Masculino")) {
                    jRadioButton1.setSelected(true);
                }
                else{
                    jRadioButton2.setSelected(true);
                }

                CONN.CERRAR();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void modificar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_btnActionPerformed

        String id = idpersonal_txt.getText();
        String nombre = nombre_txt.getText();
        String apellido = apellido_txt.getText();
        String direccion = dir_txt.getText();
        String cedula = ced_txt.getText();
        char[] pass = pass_txt.getPassword();
        String passString = new String(pass);
        String fechnac = fechnac_txt.getText();
        String area = (String) area_cbx.getSelectedItem();
        String cargo = cargo_txt.getText();
        String nacionalidad = nac_txt.getText();
        String telefono = tel_txt.getText();
        String celular = cel_txt.getText();
        String email = email_txt.getText();
        String genero = "";
        if (jRadioButton1.isSelected()) {
            genero = jRadioButton1.getText();
        } else {
            genero = jRadioButton2.getText();
        }

        try {
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost/sistema_marcado";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "123");

            String query = ("UPDATE sistema_marcado.personal SET nombre_personal = '" + nombre + "', apellido_personal='" + apellido + "',"
                    + "direccion_personal = '" + direccion + "',cedula_personal = '" + cedula + "',pass_personal = '" + passString + "',fechnac_personal = '" + fechnac + "',area_personal = '" + area + "',"
                    + "cargo_personal= '" + cargo + "',nacionalidad_personal = '" + nacionalidad + "',telefono_personal = '" + telefono + "',celular_personal ='" + celular + "',email_personal = '" + email + "',genero_personal = '" + genero + "'"
                    + "WHERE personal.id_personal = '" + id + "';");

            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.execute();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        actualizar();

    }//GEN-LAST:event_modificar_btnActionPerformed

    public void limpiar() {

        nombre_txt.setText("");
        apellido_txt.setText("");
        dir_txt.setText("");
        ced_txt.setText("");
        pass_txt.setText("");
        fechnac_txt.setText("");
        area_cbx.setSelectedIndex(0);
        cargo_txt.setText("");
        nac_txt.setText("");
        tel_txt.setText("");
        cel_txt.setText("");
        email_txt.setText("");

    }

    public void actualizar() {
        Conexion CONN = new Conexion();
        CONN.CONECTAR();
        ResultSet rs = CONN.CONSULTAR("SELECT id_personal AS ID, nombre_personal AS Nombre, direccion_personal AS Dirección, cedula_personal AS Cédula, pass_personal AS Contraseña,"
                + "fechnac_personal AS Fecha, area_personal AS Área, cargo_personal AS Cargo, nacionalidad_personal AS Nacionalidad, telefono_personal AS Teléfono,"
                + "celular_personal AS Celular, email_personal AS Email, genero_personal AS Género FROM personal order by id_personal ASC");
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Registro().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido_lbl;
    private javax.swing.JTextField apellido_txt;
    private javax.swing.JComboBox<String> area_cbx;
    private javax.swing.JLabel area_lbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JLabel cargo_lbl;
    private javax.swing.JTextField cargo_txt;
    private javax.swing.JLabel ced_lbl;
    private javax.swing.JTextField ced_txt;
    private javax.swing.JLabel cel_lbl;
    private javax.swing.JTextField cel_txt;
    private javax.swing.JLabel dir_lbl;
    private javax.swing.JTextField dir_txt;
    private javax.swing.JButton eliminar_btn;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel fechnac_lbl;
    private javax.swing.JFormattedTextField fechnac_txt;
    private javax.swing.JLabel genero_lbl;
    private javax.swing.JButton guardar_btn;
    private javax.swing.JLabel idpersonal_lbl;
    private javax.swing.JTextField idpersonal_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modificar_btn;
    private javax.swing.JLabel nac_lbl;
    private javax.swing.JTextField nac_txt;
    private javax.swing.JLabel nombre_lbl;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JLabel tel_lbl;
    private javax.swing.JTextField tel_txt;
    // End of variables declaration//GEN-END:variables
}
